export enum ModuleCode {
  EmployeeManagement = "employeeManagement",
  Employee = "employee",
  Department = "department",
  Role = "role",
  Permission = "permission",
  ProductManagement = "ProductManagement",
  Category = "category",
  Product = "product",
  WarehouseManagement = "warehouseManagement",
  Warehouse = "warehouse",
  Area = "area",
  Shelf = "shelf",
  SaleManagement = "saleManagement",
  Customer = "customer",
  PurchaseManagement = "purchaseManagement",
  Supplier = "supplier",
  PurchaseDemand = "purchaseDemand",
  PurchaseOrder = "purchaseOrder",
  PurchaseReturn = "purchaseReturn",
}
