export enum ModuleCode {
  EmployeeManagement = "employeeManagement",
  Employee = "employee",
  Department = "department",
  Role = "role",
  Permission = "permission",
  ProductManagement = "ProductManagement",
  Category = "category",
  Product = "product",
  WarehouseManagement = "warehouseManagement",
  Warehouse = "warehouse",
  Area = "area",
  Shelf = "shelf",
  SaleManagement = "saleManagement",
  Customer = "customer",
  SalesOrder = "salesOrder",
  SalesReturn = "salesReturn",
  PurchaseManagement = "purchaseManagement",
  Supplier = "supplier",
  PurchaseDemand = "purchaseDemand",
  PurchaseOrder = "purchaseOrder",
  PurchaseReturn = "purchaseReturn",
  InventoryManagement = "inventoryManagement",
  Inventory = "inventory",
  InventoryHistory = "inventoryHistory",
  InventoryCheck = "inventoryCheck",
  InventoryReceipt = "inventoryReceipt",
}
